apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: alloy-hub
    meta.helm.sh/release-namespace: observability
  labels:
    app.kubernetes.io/component: networking
    app.kubernetes.io/instance: alloy-hub
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/version: v1.4.2
    helm.sh/chart: alloy-0.9.1
  name: alloy-hub
  namespace: observability
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 12345
    protocol: TCP
    targetPort: 12345
  - port: 8126
    name: udp-statsd
    protocol: UDP
  - port: 8127
    name: tcp-statsd
    protocol: TCP
  selector:
    app.kubernetes.io/instance: alloy-hub
    app.kubernetes.io/name: alloy
  sessionAffinity: None
  type: ClusterIP