apiVersion: apps/v1
kind: Deployment
metadata:
    name: veneur-emit-3
    labels:
        app: veneur-emit-3
spec:
    minReadySeconds: 10
    replicas: 1
    selector:
        matchLabels:
            app: veneur-emit-3
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            labels:
              app: veneur-emit-3
            annotations:
              k8s.grafana.com/read-statsd: 'true' 
        spec:
          containers:
            - name: veneur-emit-3
              image: index.docker.io/stripe/veneur:3.0.0
              imagePullPolicy: Always
              command: ["/bin/sh"]
              args: ["-c", "while true; do veneur-emit -debug -hostport udp://alloy-hub.observability.svc.cluster.local:8126 -name 'my.test.timer' -timing '100ms'; sleep 10; done"]
            - name: veneur
              image: index.docker.io/stripe/veneur:3.0.0
              ports:
              - containerPort: 8127
                name: healthcheck
                protocol: TCP
              livenessProbe:
                httpGet:
                  path: /healthcheck
                  port: 8127
              env:
                  - name: VENEUR_NUMWORKERS
                    value: "3"
          terminationGracePeriodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: veneur-service-3
  labels:
    app: veneur-emit-3
  annotations:
    k8s.grafana.com/read-statsd: 'true'
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  ports:
  - name: healthcheck
    port: 8127
    protocol: TCP
    targetPort: 8127
